### ISSUE TITLE
R28_Java8 NumberFormatException

### ISSUE THREAD

**Issue by acailley** [chewiebug/GCViewer#175]
Hi,

I have a NumberFormatException with my files in IBM R28_Java8 :
INFOS [DataReaderFacade]: GCViewer version 1.35-SNAPSHOT (2016-04-19T19:37:12+0000)
INFOS [DataReaderFactory]: File format: IBM J9 R26 / R27 / R28
AVERTISSEMENT [DataReaderFacade]: La lecture du journal a echoué.
java.lang.NumberFormatException: 6442450944 6442450944
AVERTISSEMENT [GCModelLoaderImpl]: Failed to create GCModel from C:\work\echange\OCT150518\GC_IS_PRJ_55110_160804_090423.log
java.util.concurrent.ExecutionException: com.tagtraum.perf.gcviewer.imp.DataReaderException
	at java.util.concurrent.FutureTask.report(Unknown Source)
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at javax.swing.SwingWorker.get(Unknown Source)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCModelLoaderImpl.done(GCModelLoaderImpl.java:57)
	at javax.swing.SwingWorker$5.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at sun.swing.AccumulativeRunnable.run(Unknown Source)
	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at javax.swing.Timer.fireActionPerformed(Unknown Source)
	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

[GC_IS_PRJ_55110_160804_090423.zip](https://github.com/chewiebug/GCViewer/files/410918/GC_IS_PRJ_55110_160804_090423.zip)

thanks for your help !

**Comment by chewiebug** [comment]
Hi,

Thank you for the sample log - it seems to contain more types of events, 
than the files, I had seen up to now. I will have to look into the 
parser, to see, how I can get it to parse this file.

Best regards,
Jörg

**Comment by acailley** [comment]
Hi,
thanks for your reply.
Our jvm option on gc are : 
-XX:SurvivorRatio=8
-XX:NewRatio=4
-XX:+HeapDumpOnOutOfMemoryError
-XX:-UseAdaptiveSizePolicy
-XX:+UseThreadPriorities
-verbose:gc
-XX:+PrintGC
-XX:+PrintGCDetails
-XX:+PrintGCTimeStamps
-Xverbosegclog:/logs/mypath/GC_myinstance_%y%m%d_%H%M%S.log
-Xgcpolicy:optavgpause
-Xms6144m
-Xmx6144m

**Comment by chewiebug** [comment]
Hi, I have pushed a fix, that allows you to read your log file. The 
parser misses the difference between af and sys collections, but at 
least, you can now see something.

The latest build is available here: 
https://github.com/chewiebug/GCViewer/wiki/Changelog (1.35-SNAPSHOT).

Best regards,
Jörg

**Comment by acailley** [comment]
Hi !
it seems to work fine !
I am used to Oracle jvm and I must confess that I am a little bit lost with the result of this log on GCviewer. Where is my new generation ???
Anyway thanks a lot for your uberfast evolution !!

Best Regards,
Alain

**Comment by chewiebug** [comment]
Hi

Cool! I have implemented an additional feature: GCViewer now recognises 
"af" and "sys" gc events (the latest build contains these improvements).

I am also much more used to the Oracle jvm. I first thought, there was a 
bug in the parser, but it really looks like, there is only the tenured 
generation in your log file.

Do you know http://www.ibm.com/developerworks/java/jdk/tools/gcmv/? I 
think that tool might help you a lot with IBM gc logs. For your log, the 
summary is this:


What do you think about 
http://www-01.ibm.com/support/docview.wss?uid=swg27013824&aid=1? Looks 
interesting to me, if you need to tune an IBM JVM.

I like "uberfast" (didn't know, that the word exists) :-).

Best regards, Jörg

**Comment by acailley** [comment]
Hi !
I also figured out that with Xgcpolicy optavgpause there is only tenured generation.
There is a "nursery" (new gen) with Xgcpolicy gencon, more like what we are used in Oracle/sun jvm.


here is a sample file with gencon :

[prj41_GC_IS_PRJ_55110_160817_142133-gencon.zip](https://github.com/chewiebug/GCViewer/files/423024/prj41_GC_IS_PRJ_55110_160817_142133-gencon.zip)

I know GCMV, but honestly I do not like it.
Another quite powerfull tool is "ibm pattern modeling and analysis tool for java garbage collector" (what a name !!)

[https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=22d56091-3a7b-4497-b36e-634b51838e11](https://www.ibm.com/developerworks/community/groups/service/html/communityview?communityUuid=22d56091-3a7b-4497-b36e-634b51838e11)

**Comment by acailley** [comment]
for [http://www-01.ibm.com/support/docview.wss?uid=swg27013824&aid=1](http://www-01.ibm.com/support/docview.wss?uid=swg27013824&aid=1)
I also read it (very interesting indeed) it is with the results page 25 that convinced me to swith bach to gencon.
I do not have yet produiced a full GC but, I have pauses that take very less time, and global performance increased by 100%.
Quite strange when optavgpause is meant to generate fewer and faster pauses and at a 10% overcost.
Must have mised something or need more tuning !

**Comment by acailley** [comment]
Another gencon log, with a "fullGC".
I expected the memory to go under 1Go, don't know why it did not happen !
Also, this "fullGc" did not take much time. Strange....

[med4_GC_IS_MED_55130_160817_181254.zip](https://github.com/chewiebug/GCViewer/files/423074/med4_GC_IS_MED_55130_160817_181254.zip)

nice new release ! optavgpause is MUCH more readable. :)
