### ISSUE TITLE
Java 1.8 u92 NumberFormatException: null

### ISSUE THREAD

**Issue by vrtareg** [chewiebug/GCViewer#180]
Hi

Not sure if it is related to #175 but I see following on command line run:

```
[jira@jira gcviewer]$ java -jar gcviewer-1.35-SNAPSHOT.jar /jira/logs/jira/gc.log.0.current  summary.csv chart.png
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.GCViewer doMain
INFO: GCViewer command line mode
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderFacade loadModel
INFO: GCViewer version 1.35-SNAPSHOT (2016-08-17T15:29:33+0000)
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderFactory getDataReaderBySample
INFO: File format: Sun 1.6.x G1 collector
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
INFO: Reading Sun 1.6.x / 1.7.x G1 format...
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
INFO: Java HotSpot(TM) 64-Bit Server VM (25.92-b14) for linux-amd64 JRE (1.8.0_92-b14), built on Mar 31 2016 21:08:29 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
INFO: Memory: 4k page, physical 395961680k(360959988k free), swap 2047996k(2047996k free)
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
INFO: CommandLine flags: -XX:+DisableExplicitGC -XX:GCLogFileSize=26214400 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/jira/home/../logs/java_heapdump/ -XX:InitialHeapSize=6442450944 -XX:+ManagementServer -XX:MaxHeapSize=6442450944 -XX:NumberOfGCLogFiles=1000 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:ReservedCodeCacheSize=402653184 -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseGCLogFileRotation -XX:-UseGCOverheadLimit 
Oct 13, 2016 6:08:39 AM com.tagtraum.perf.gcviewer.imp.DataReaderSun1_6_0G1 read
INFO: Done reading.
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.tagtraum.perf.gcviewer.view.model.GCPreferences.getIntValue(GCPreferences.java:197)
        at com.tagtraum.perf.gcviewer.view.model.GCPreferences.getWindowWidth(GCPreferences.java:118)
        at com.tagtraum.perf.gcviewer.view.SimpleChartRenderer.render(SimpleChartRenderer.java:25)
        at com.tagtraum.perf.gcviewer.GCViewer.renderChart(GCViewer.java:101)
        at com.tagtraum.perf.gcviewer.GCViewer.export(GCViewer.java:90)
        at com.tagtraum.perf.gcviewer.GCViewer.doMain(GCViewer.java:68)
        at com.tagtraum.perf.gcviewer.GCViewer.main(GCViewer.java:42)
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:542)
        at java.lang.Integer.parseInt(Integer.java:615)
        at com.tagtraum.perf.gcviewer.view.model.GCPreferences.getIntValue(GCPreferences.java:197)
        at com.tagtraum.perf.gcviewer.view.model.GCPreferences.getWindowHeight(GCPreferences.java:126)
        at com.tagtraum.perf.gcviewer.view.SimpleChartRenderer.render(SimpleChartRenderer.java:25)
        at com.tagtraum.perf.gcviewer.GCViewer.renderChart(GCViewer.java:101)
        at com.tagtraum.perf.gcviewer.GCViewer.export(GCViewer.java:90)
        at com.tagtraum.perf.gcviewer.GCViewer.doMain(GCViewer.java:68)
        at com.tagtraum.perf.gcviewer.GCViewer.main(GCViewer.java:42)
Oct 13, 2016 6:08:40 AM com.tagtraum.perf.gcviewer.GCViewer doMain
INFO: export completed successfully
```

**Comment by vrtareg** [comment]
Looks like that GUI mode is ok.

**Comment by chewiebug** [comment]
Hi,

No, it is not related to #175. Commandline mode of GCViewer with your 
parameters tries to read window width + height from the properties file 
to determine the size of the image to generate. If this fails, defaults 
are used - and the stacktrace is output to the console, as well. It 
should probably write something less ugly, than this.

The reason for the stacktrace and the usage of defaults is, that 
GCViewer didn't find a properties file to read the values from. I 
assume, that you never started GCViewer with the gui before.

Best regards,
Jörg

**Comment by vrtareg** [comment]
Thanks a lot.
