### ISSUE TITLE
Cannot build on Debian

### ISSUE THREAD

**Issue by Pablohn26** [chewiebug/GCViewer#209]
I cannot build the project with 

> mvn clean install

after just cloning the repo.  The problem is one of the test is failing:

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.977 s
[INFO] Finished at: 2018-11-08T17:00:33+01:00
[INFO] Final Memory: 28M/487M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project gcviewer: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/phinojosa/test/GCViewer/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/phinojosa/test/GCViewer && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -javaagent:/home/phinojosa/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/phinojosa/test/GCViewer/target/jacoco.exec -jar /home/phinojosa/test/GCViewer/target/surefire/surefirebooter5429627807982103207.jar /home/phinojosa/test/GCViewer/target/surefire 2018-11-08T17-00-32_771-jvmRun1 surefire6635421196090447877tmp surefire_08441888979935462648tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/phinojosa/test/GCViewer && /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -javaagent:/home/phinojosa/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/phinojosa/test/GCViewer/target/jacoco.exec -jar /home/phinojosa/test/GCViewer/target/surefire/surefirebooter5429627807982103207.jar /home/phinojosa/test/GCViewer/target/surefire 2018-11-08T17-00-32_771-jvmRun1 surefire6635421196090447877tmp surefire_08441888979935462648tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 1
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:669)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR] at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR] at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

Versions are

```
mvn -version
Apache Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_181, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-8-amd64", arch: "amd64", family: "unix"

```

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch

```

and I attach the full log.

[log.txt](https://github.com/chewiebug/GCViewer/files/2562467/log.txt)

**Comment by ecki** [comment]
Is this a random crash or is it repeatable? (i.e. happens every time). Can you also check the dumpfile so we can see what the stdout message of the crashed JVM is. Do you see any hs_err files?

**Comment by hbswn** [comment]
For me it works on Debian 9
`
mvn test
. . .
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 377, Failures: 0, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2019-06-08T23:08:11+02:00
[INFO] Final Memory: 13M/97M
[INFO] ------------------------------------------------------------------------
`
Maven version:
`
Maven 3.3.9
Maven home: /usr/share/maven
Java version: 1.8.0_212, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-9-amd64", arch: "amd64", family: "unix"
`

**Comment by hbswn** [comment]
I'd suggest the original author to use the hints by Maven:
```
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

The cause is not in the default output. I guess it's some missing `jar` or so.

**Comment by hbswn** [comment]
The output of `mvn clean install`:
```
[INFO] Installing /home/hans/workspace/GCViewer/pom.xml to /home/hans/.m2/repository/com/github/chewiebug/gcviewer/1.36-SNAPSHOT/gcviewer-1.36-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:03 min
[INFO] Finished at: 2019-06-08T23:27:05+02:00
[INFO] Final Memory: 30M/263M
[INFO] ------------------------------------------------------------------------
...

`target` directory:
```
total 660
drwxr-xr-x 3 hans hans   4096 Jun  8 23:26 mac
drwxr-xr-x 3 hans hans   4096 Jun  8 23:26 maven-status
drwxr-xr-x 3 hans hans   4096 Jun  8 23:26 generated-sources
drwxr-xr-x 5 hans hans   4096 Jun  8 23:26 classes
drwxr-xr-x 3 hans hans   4096 Jun  8 23:26 generated-test-sources
drwxr-xr-x 8 hans hans   4096 Jun  8 23:26 test-classes
-rw-r--r-- 1 hans hans     66 Jun  8 23:26 export.csv
-rw-r--r-- 1 hans hans  10834 Jun  8 23:26 export.png
drwxr-xr-x 2 hans hans  16384 Jun  8 23:26 surefire-reports
-rw-r--r-- 1 hans hans  46665 Jun  8 23:27 jacoco.exec
drwxr-xr-x 3 hans hans   4096 Jun  8 23:27 site
drwxr-xr-x 2 hans hans   4096 Jun  8 23:27 maven-archiver
-rw-r--r-- 1 hans hans 556097 Jun  8 23:27 gcviewer-1.36-SNAPSHOT.jar
```

**Comment by Pablohn26** [comment]
I have tried again now in debian 10 and using next command the build success

`JAVA_HOME=/usr/lib/jvm/default-java mvn clean install`

So we can close this issue

**Comment by chewiebug** [comment]
Very nice! Thank you very much!
