### ISSUE TITLE
GCViewer fails to parse unified logging format

### ISSUE THREAD

**Issue by Norbo11** [chewiebug/GCViewer#217]
Hi, as per the readme.md, I have ran my application with these VM settings:

-Xlog:gc=info:file=\"C:\Users\npodsadowski\Desktop\gc-long.log\":tags,uptime,level

When I try to open the file in GCViewer, it fails:

```
INFO [DataReaderFacade]: GCViewer version 1.35 (2017-06-28T16:44:25+0200)
SEVERE [DataReaderFactory]: Failed to recognize file format.
content:
[2.951s][info][gc] GC(83) Concurrent Cycle 4.597ms
[2.970s][info][gc] GC(84) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.765ms
[2.970s][info][gc] GC(85) Concurrent Cycle
[2.973s][info][gc] GC(85) Pause Remark 49M->49M(1121M) 0.873ms
[2.973s][info][gc] GC(85) Pause Cleanup 58M->58M(1121M) 0.409ms
[2.975s][info][gc] GC(85) Concurrent Cycle 4.711ms
[2.993s][info][gc] GC(86) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.806ms
[2.993s][info][gc] GC(87) Concurrent Cycle
[2.996s][info][gc] GC(87) Pause Remark 44M->44M(1121M) 0.874ms
[2.997s][info][gc] GC(87) Pause Cleanup 52M->52M(1121M) 0.502ms
[2.998s][info][gc] GC(87) Concurrent Cycle 4.662ms
[3.017s][info][gc] GC(88) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.756ms
[3.017s][info][gc] GC(89) Concurrent Cycle
[3.020s][info][gc] GC(89) Pause Remark 47M->47M(1121M) 0.858ms
[3.021s][info][gc] GC(89) Pause Cleanup 56M->56M(1121M) 0.399ms
[3.022s][info][gc] GC(89) Concurrent Cycle 4.571ms
[3.041s][info][gc] GC(90) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.700ms
[3.041s][info][gc] GC(91) Concurrent Cycle
[3.043s][info][gc] GC(91) Pause Remark 46M->46M(1121M) 0.894ms
[3.044s][info][gc] GC(91) Pause Cleanup 55M->55M(1121M) 0.461ms
[3.045s][info][gc] GC(91) Concurrent Cycle 4.708ms
[3.067s][info][gc] GC(92) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.865ms
[3.067s][info][gc] GC(93) Concurrent Cycle
[3.071s][info][gc] GC(93) Pause Remark 51M->51M(1121M) 0.906ms
[3.072s][info][gc] GC(93) Pause Cleanup 62M->62M(1121M) 0.463ms
[3.073s][info][gc] GC(93) Concurrent Cycle 5.447ms
[3.092s][info][gc] GC(94) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.798ms
[3.092s][info][gc] GC(95) Concurrent Cycle
[3.095s][info][gc] GC(95) Pause Remark 47M->47M(1121M) 0.911ms
[3.096s][info][gc] GC(95) Pause Cleanup 56M->56M(1121M) 0.445ms
[3.097s][info][gc] GC(95) Concurrent Cycle 4.766ms
[3.117s][info][gc] GC(96) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.743ms
[3.117s][info][gc] GC(97) Concurrent Cycle
[3.119s][info][gc] GC(97) Pause Remark 45M->45M(1121M) 0.889ms
[3.120s][info][gc] GC(97) Pause Cleanup 54M->54M(1121M) 0.386ms
[3.121s][info][gc] GC(97) Concurrent Cycle 4.671ms
[3.141s][info][gc] GC(98) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.816ms
[3.141s][info][gc] GC(99) Concurrent Cycle
[3.144s][info][gc] GC(99) Pause Remark 45M->45M(1121M) 0.875ms
[3.145s][info][gc] GC(99) Pause Cleanup 54M->54M(1121M) 0.572ms
[3.146s][info][gc] GC(99) Concurrent Cycle 5.159ms
[3.165s][info][gc] GC(100) Pause Initial Mark (G1 Humongous Allocation) 504M->5M(1121M) 0.850ms
[3.166s][info][gc] GC(101) Concurrent Cycle
[3.168s][info][gc] GC(101) Pause Remark 48M->48M(1121M) 0.884ms
[3.169s][info][gc] GC(101) Pause Cleanup 57M->57M(1121M) 0.440ms
[3.170s][info][gc] GC(101) Concurrent Cycle 4.724ms

WARNING [DataReaderFacade]: Failed to read file.
java.io.IOException: Failed to recognize file format. Failed to recognize file format.
WARNING [AbstractGCModelLoaderImpl]: Failed to create GCModel from C:\Users\npodsadowski\Desktop\gc-long.log
java.util.concurrent.ExecutionException: java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.get(Unknown Source)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.done(AbstractGCModelLoaderImpl.java:31)
	at java.desktop/javax.swing.SwingWorker$5.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
	at java.desktop/sun.swing.AccumulativeRunnable.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Unknown Source)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out-of-bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
	at java.base/java.util.Objects.checkIndex(Unknown Source)
	at java.base/java.util.ArrayList.get(Unknown Source)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GcSeriesLoader.mergeModels(GcSeriesLoader.java:123)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GcSeriesLoader.load(GcSeriesLoader.java:38)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.loadModelFromSeries(DataReaderFacade.java:92)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.loadModel(DataReaderFacade.java:56)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCModelSeriesLoaderImpl.loadGcModel(GCModelSeriesLoaderImpl.java:31)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.doInBackground(AbstractGCModelLoaderImpl.java:49)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.doInBackground(AbstractGCModelLoaderImpl.java:19)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

```

**Comment by Norbo11** [comment]
Originally, I was running this with Oracle JDK, and I thought that may have been the issue.

I have just tried running my application with Open JDK, and I got the same error.

**Comment by chewiebug** [comment]
Hi Norbert,

Please use the latest version of GCViewer (1.36-SNAPSHOT -> 
https://github.com/chewiebug/GCViewer/wiki/Changelog). It will parse 
your log.

Best regards,
Jörg
