### ISSUE TITLE
java.io.IOException: Failed to recognize file format. Failed to recognize file format. on java 11

### ISSUE THREAD

**Issue by duncte123** [chewiebug/GCViewer#225]
The logs were generated with the following command `java -Xlog:gc*=trace:file="gclogs/gc.log":tags,time,uptime,level -jar Lavalink.jar`

I am running a java 11 vm
```
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
```

And while loading in the generated log (attached as file) the following stacktrace occurred.
```
Aug 09, 2019 11:37:30 AM com.tagtraum.perf.gcviewer.imp.DataReaderFacade loadModel
INFO: GCViewer version 1.35 (2017-06-28T16:44:25+0200)
Aug 09, 2019 11:37:30 AM com.tagtraum.perf.gcviewer.imp.DataReaderFactory getDataReader
SEVERE: Failed to recognize file format.
content:
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  46|0x0000000088000000, 0x0000000088000000, 0x0000000088100000|  0%| F|  |TAMS 0x0000000088000000, 0x0000000088000000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  47|0x0000000088100000, 0x0000000088100000, 0x0000000088200000|  0%| F|  |TAMS 0x0000000088100000, 0x0000000088100000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  48|0x0000000088200000, 0x0000000088200000, 0x0000000088300000|  0%| F|  |TAMS 0x0000000088200000, 0x0000000088200000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  49|0x0000000088300000, 0x0000000088300000, 0x0000000088400000|  0%| F|  |TAMS 0x0000000088300000, 0x0000000088300000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  50|0x0000000088400000, 0x0000000088400000, 0x0000000088500000|  0%| F|  |TAMS 0x0000000088400000, 0x0000000088400000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  51|0x0000000088500000, 0x0000000088500000, 0x0000000088600000|  0%| F|  |TAMS 0x0000000088500000, 0x0000000088500000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  52|0x0000000088600000, 0x0000000088600000, 0x0000000088700000|  0%| F|  |TAMS 0x0000000088600000, 0x0000000088600000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  53|0x0000000088700000, 0x0000000088700000, 0x0000000088800000|  0%| F|  |TAMS 0x0000000088700000, 0x0000000088700000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  54|0x0000000088800000, 0x0000000088800000, 0x0000000088900000|  0%| F|  |TAMS 0x0000000088800000, 0x0000000088800000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  55|0x0000000088900000, 0x0000000088900000, 0x0000000088a00000|  0%| F|  |TAMS 0x0000000088900000, 0x0000000088900000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  56|0x0000000088a00000, 0x0000000088a00000, 0x0000000088b00000|  0%| F|  |TAMS 0x0000000088a00000, 0x0000000088a00000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  57|0x0000000088b00000, 0x0000000088b00000, 0x0000000088c00000|  0%| F|  |TAMS 0x0000000088b00000, 0x0000000088b00000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  58|0x0000000088c00000, 0x0000000088c00000, 0x0000000088d00000|  0%| F|  |TAMS 0x0000000088c00000, 0x0000000088c00000| Untracked 
[2019-08-09T09:57:06.869+0200][0,297s][trace][gc,heap,region              ] GC(0) |  59|0x0000000088d00000, 0x0000000088d00000, 0x0000000088e00000|  0%| F|  |TAMS 0x0000000088d00000, 0x0000000088d00000| Untracked 

Aug 09, 2019 11:37:30 AM com.tagtraum.perf.gcviewer.imp.DataReaderFacade loadModel
WARNING: Failed to read file.
java.io.IOException: Failed to recognize file format. Failed to recognize file format.
Aug 09, 2019 11:37:30 AM com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl done
WARNING: Failed to create GCModel from /home/duncte123/Downloads/lavalink/gclogs/gc.log
java.util.concurrent.ExecutionException: com.tagtraum.perf.gcviewer.imp.DataReaderException
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.done(AbstractGCModelLoaderImpl.java:31)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:847)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:857)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.tagtraum.perf.gcviewer.imp.DataReaderException
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.loadModel(DataReaderFacade.java:61)
	at com.tagtraum.perf.gcviewer.ctrl.impl.GCModelLoaderImpl.loadGcModel(GCModelLoaderImpl.java:29)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.doInBackground(AbstractGCModelLoaderImpl.java:49)
	at com.tagtraum.perf.gcviewer.ctrl.impl.AbstractGCModelLoaderImpl.doInBackground(AbstractGCModelLoaderImpl.java:19)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: Failed to recognize file format.
	at com.tagtraum.perf.gcviewer.imp.DataReaderFactory.getDataReader(DataReaderFactory.java:92)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.readModel(DataReaderFacade.java:129)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.loadModel(DataReaderFacade.java:68)
	... 9 more
```

Generated GC log from application: 
[gc.log](https://github.com/chewiebug/GCViewer/files/3485733/gc.log)

**Comment by chewiebug** [comment]
Hi Duncan,

Please use the latest SNAPSHOT version of GCViewer (you may download it
here: https://github.com/chewiebug/GCViewer/wiki/Changelog). It will
parse your log.

Best regards,
Jörg

**Comment by duncte123** [comment]
Awesome, thank you

**Comment by chewiebug** [comment]
You are welcome!
