### ISSUE TITLE
Error parsing openjdk 11 logs

### ISSUE THREAD

**Issue by mkrichevsky** [chewiebug/GCViewer#241]
I have a service running openJDK 11.0.5 with following flags: `-XX:+PrintGCDetails` `-Xlog:gc=info:file=gc.log:utc,tid,uptime`
When I open the log file I get an error
`Caused by: java.io.IOException: Failed to recognize file format.
	at com.tagtraum.perf.gcviewer.imp.DataReaderFactory.getDataReader(DataReaderFactory.java:92)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.readModel(DataReaderFacade.java:132)
	at com.tagtraum.perf.gcviewer.imp.DataReaderFacade.loadModel(DataReaderFacade.java:68)`

What could be the issue?

Thanks in advance for looking into this.

**Comment by mkrichevsky** [comment]
It seems that I need to have tags enabled in order for parsing to work correctly
