### ISSUE TITLE
Error when open file

### ISSUE THREAD

**Issue by haithamhesham** [chewiebug/GCViewer#249]
WARNING [DataReaderSun1_5_0]: java.lang.NumberFormatException: For input string: "Java HotSpot(TM) 64-Bit Server VM (25.251-b08) for linux-amd64 JRE (1.8.0_251-b08). built on Mar 11 2020 23" while parsing line: Java HotSpot(TM) 64-Bit Server VM (25.251-b08) for linux-amd64 JRE (1.8.0_251-b08), built on Mar 11 2020 23:20:16 by "java_re" with gcc 7.3.0
java.lang.NumberFormatException: For input string: "Java HotSpot(TM) 64-Bit Server VM (25.251-b08) for linux-amd64 JRE (1.8.0_251-b08). built on Mar 11 2020 23"
	at sun.misc.FloatingDecimal.readJavaFormatString(Unknown Source)
	at sun.misc.FloatingDecimal.parseDouble(Unknown Source)
	at java.lang.Double.parseDouble(Unknown Source)
	at com.tagtraum.perf.gcviewer.imp.AbstractDataReaderSun.parseTimestamp(AbstractDataReaderSun.java:215)
	at com.tagtraum.perf.gcviewer.imp.DataReaderSun1_5_0.parseLine(DataReaderSun1_5_0.java:32)
	at com.tagtraum.perf.gcviewer.imp.DataReaderSun1_4_0.read(DataReaderSun1_4_0.java:77)
	at com.tagtraum.perf.gcviewer.ChartPanelView.loadModel(ChartPanelView.java:77)
	at com.tagtraum.perf.gcviewer.ChartPanelView.<init>(ChartPanelView.java:52)
	at com.tagtraum.perf.gcviewer.GCDocument.add(GCDocument.java:118)
	at com.tagtraum.perf.gcviewer.GCViewer.add(GCViewer.java:272)
	at com.tagtraum.perf.gcviewer.GCViewer.add(GCViewer.java:258)
	at com.tagtraum.perf.gcviewer.action.OpenFile.actionPerformed(OpenFile.java:59)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by haithamhesham** [comment]
run GCViewer using Oracle Java build 1.8.0_251-b08

**Comment by chewiebug** [comment]
Hi

GCViewer has an automatic file format detection, which sometimes results
in using an inapropriate parser for the log file at hand. The error
message provided unfortunately does not include enough information for
me to help.

Which version of GCViewer are you using? Could you please attach a
sample of the logfile you are trying to parse? The beginning of the file
is the most important part, because that is, where GCViewer tries to
decide on the parser to use.

Best regards
Jörg
